### ISSUE TITLE
Example script gives an error

### ISSUE THREAD

**Issue by blaisn** [doberkofler/web_plsql#6]
Hi,
After example script correction (see issue #5), I get an error when running it:
´´´
node index
Waiting on http://localhost:8000/pls/sample

ERROR
=====
TypeError: e.stack is not a function
    at C:\sources\web-plsql\node_modules\web_plsql\lib\procedure.js:317:86
    at Generator.throw (<anonymous>)
    at rejected (C:\sources\web-plsql\node_modules\web_plsql\lib\procedure.js:8:65)

REQUEST
=======
{ originalUrl: '/pls/sample/sample.pageIndex',
  params: { name: 'sample.pageIndex' },
  query: {},
  url: '/',
  method: 'GET',
  body: {},
  files: {},
  cookies: [Object: null prototype] {} }
´´´
Thanks

**Comment by doberkofler** [comment]
I was not able to reproduce this problem. Could you please try again with 0.2.0?

**Comment by doberkofler** [comment]
I am closing this SR as it cannot be reproduced
